name: flutter_website
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^3.0.0
  flutter_webview_plugin: ^0.3.10
  flutter_swiper: ^1.1.6
  fluttertoast: ^3.1.3
  #json
  json_serializable: ^2.0.0
  json_model: ^0.0.2
  build_runner: ^1.0.0
  #路由
  fluro: "^1.6.0"
  #日期格式化
  date_format: ^1.0.8
  #评分
  flutter_rating_bar: ^3.0.1
  #日期组件
  flutter_datetime_picker: ^1.3.5



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/3.0x/bg_splash.jpg



